<div class="col-lg-8 col-md-offset-2">
    <!-- posts -->
    <?php foreach ($this->list as $post) {
    ?>
    <!-- social-feed-box -->
    <div class="social-feed-box">
        <!-- social-action -->
        <div class="pull-right social-action dropdown">
            <button data-toggle="dropdown" class="dropdown-toggle btn-white">
                <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu m-t-xs">
                <li><a href="#">Config</a></li>
            </ul>
        </div>
        <!-- end social-action -->
        <!-- social-avatar -->
        <div class="social-avatar">
            <a href="" class="pull-left">
                <img alt="image" src="img/a1.jpg">
            </a>

            <div class="media-body">
                <a href="#">
                    <?php echo($post->getUserName()); ?>
                </a>
                <small class="text-muted">Today 4:21 pm - 12.06.2014</small>
            </div>
        </div>
        <!-- end social-avatar -->
        <!-- social-body -->
        <div class="social-body">
            <p>
                Many desktop publishing packages and web page editors now use Lorem Ipsum as their
                default model text, and a search for 'lorem ipsum' will uncover many web sites still
                in their infancy. Packages and web page editors now use Lorem Ipsum as their
                default model text.
            </p>

            <div class="btn-group">
                <button class="btn btn-white btn-xs"><i class="fa fa-thumbs-up"></i> Like this!</button>
                <button class="btn btn-white btn-xs"><i class="fa fa-comments"></i> Comment</button>
                <button class="btn btn-white btn-xs"><i class="fa fa-share"></i> Share</button>
            </div>
        </div>
        <!-- end social-body -->
        <!-- social-footer -->
        <div class="social-footer">
            <!-- social-comment -->
            <div class="social-comment">
                <a href="" class="pull-left">
                    <img alt="image" src="img/a1.jpg">
                </a>

                <div class="media-body">
                    <a href="#">
                        Andrew Williams
                    </a>
                    Internet tend to repeat predefined chunks as necessary, making this the first true generator on the
                    Internet. It uses a dictionary of over 200 Latin words.
                    <br>
                    <a href="#" class="small"><i class="fa fa-thumbs-up"></i> 26 Like this!</a> -
                    <small class="text-muted">12.06.2014</small>
                </div>
            </div>
            <!-- end social-comment -->
            <!-- social-comment -->
            <div class="social-comment">
                <a href="" class="pull-left">
                    <img alt="image" src="img/a2.jpg">
                </a>

                <div class="media-body">
                    <a href="#">
                        Andrew Williams
                    </a>
                    Making this the first true generator on the Internet. It uses a dictionary of.
                    <br>
                    <a href="#" class="small"><i class="fa fa-thumbs-up"></i> 11 Like this!</a> -
                    <small class="text-muted">10.07.2014</small>
                </div>
            </div>
            <!-- end social-comment -->
            <!-- social-comment -->
            <div class="social-comment">
                <a href="" class="pull-left">
                    <img alt="image" src="img/a3.jpg">
                </a>

                <div class="media-body">
                    <textarea class="form-control" placeholder="Write comment..."></textarea>
                </div>
            </div>
            <!-- end social-comment -->
        </div>
        <!-- end social-footer -->
    </div>
    <!--end social-feed-box -->
<?php
}
?>
</div>
<!-- end col-lg-8 col-md-offset-2 -->